proveedor_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProveedorBundle:Default:index }

proveedor_list:
    path:   /
    defaults: { _controller: ProveedorBundle:Proveedor:index }

proveedor_new:
    path:   /new
    defaults: { _controller: ProveedorBundle:Proveedor:new }
    methods:  [GET,POST]

proveedor_show:
    path: /show/{id}
    defaults: { _controller: ProveedorBundle:Proveedor:show, id: 1 }
    methods:  [GET]
    requirements:
        id:   \d+

proveedor_edit:
    path: /edit/{id}
    defaults: { _controller: ProveedorBundle:Proveedor:edit }
#    methods:  [GET, POST]
    requirements:
        id:   \d+

proveedor_delete:
    path: /delete/{id}
    defaults: { _controller: ProveedorBundle:Proveedor:delete, id: null }
    methods:  [GET]
    requirements:
        id:   \d+