parameters:
#    proveedor.example.class: Ventas\ProveedorBundle\Example

services:
#    proveedor.example:
#        class: %proveedor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
